# Generated by Django 5.2.7 on 2025-11-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_habitacion', models.CharField(max_length=3, unique=True)),
                ('tipo', models.CharField(choices=[('suite', 'Suite'), ('vista_al_mar', 'Vista Al Mar'), ('sencilla', 'Sencilla'), ('doble', 'Doble')])),
                ('precio_por_noche', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='habitaciones/')),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
